###
POST http://127.0.0.1:5000/api/new_session/player1

###
POST http://127.0.0.1:5000/api/new_session/player2


###
POST http://127.0.0.1:5000/api/add_credits/player1

###
POST http://127.0.0.1:5000/api/add_credits/player2

###
POST http://127.0.0.1:5000/api/start_game/player1

> {% client.global.set('id', response.body.id); %}

###
POST http://127.0.0.1:5000/api/start_game/player2




###
GET http://127.0.0.1:5000/api/board/{{ id }}


###
POST http://127.0.0.1:5000/api/move/{{ id }}/player1
content-type: application/json

{
    "col": 0,
     "row": 0
}

###
POST http://127.0.0.1:5000/api/move/{{ id }}/player2
content-type: application/json

{
    "col": 0,
     "row": 1
}

###
POST http://127.0.0.1:5000/api/move/{{ id }}/player1
content-type: application/json

{
    "col": 1,
     "row": 0
}

###
POST http://127.0.0.1:5000/api/move/{{ id }}/player2
content-type: application/json

{
    "col": 1,
     "row": 1
}

###
POST http://127.0.0.1:5000/api/move/{{ id }}/player1
content-type: application/json

{
    "col": 1,
     "row": 2
}

###
POST http://127.0.0.1:5000/api/move/{{ id }}/player2
content-type: application/json

{
    "col": 2,
     "row": 1
}
###
GET http://127.0.0.1:5000/api/get_stats
content-type: application/json