"""empty message

Revision ID: 3f1cd9d8bc40
Revises: b62b384f44b9
Create Date: 2023-06-12 17:41:53.186964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1cd9d8bc40'
down_revision = 'b62b384f44b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_symbol_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint('player_symbol_key', ['symbol'])

    # ### end Alembic commands ###
