"""empty message

Revision ID: 91dcf42dbe51
Revises: dee46c10912e
Create Date: 2023-06-10 10:59:23.409405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dcf42dbe51'
down_revision = 'dee46c10912e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('symbol')

    op.create_table('game',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ties', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_name'], ['player.name'], name='game_player_name_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_pkey')
    )
    # ### end Alembic commands ###
