"""changed game model 2

Revision ID: c523eb42da85
Revises: e6871fff80e0
Create Date: 2023-06-11 09:53:41.897164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c523eb42da85'
down_revision = 'e6871fff80e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('losses', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'player', ['losses'], ['name'])
        batch_op.create_foreign_key(None, 'player', ['wins'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
