"""Add data to player table

Revision ID: dee46c10912e
Revises: e6fc97cefd8f
Create Date: 2023-06-06 12:31:49.267581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee46c10912e'
down_revision = '9b60151cfe9c'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    metadata = sa.MetaData()
    metadata.reflect(bind=connection)
    player_table = metadata.tables['player']

    op.bulk_insert(
        player_table,
        [
            {'name': 'player1', 'credits': 10, 'symbol': 'X'},
            {'name': 'player2', 'credits': 10, 'symbol': 'O'},
        ]
    )
    # ### end Alembic commands ###

