"""changed game model 3

Revision ID: f36ed62dac67
Revises: c523eb42da85
Create Date: 2023-06-11 10:09:44.704244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36ed62dac67'
down_revision = 'c523eb42da85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('game_losses_fkey', type_='foreignkey')
        batch_op.drop_column('losses')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('losses', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('game_losses_fkey', 'player', ['losses'], ['name'])

    # ### end Alembic commands ###
